# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"downsample": "00_training.balance.ipynb",
         "upsample": "00_training.balance.ipynb",
         "balance": "00_training.balance.ipynb"}

modules = ["training/balance.py"]

doc_url = "https://maronr.github.io/ds_helpers/"

git_url = "https://github.com/maronr/ds_helpers/tree/master/"

def custom_doc_links(name): return None
